### ISSUE TITLE
Do not forget to close the connections after work is done.

### ISSUE THREAD

**Issue by sahil070197** [ciphereck/NIT-KKR-WEBSITE#4]
No connection has been closed. Close every connection after using it.

**Comment by naman-gupta99** [comment]
If the connection is closed it cannot run the database in the nav_bar.js please find a solution.

**Comment by sahil070197** [comment]
Whenever .js file will access the database, it will create a new connection and close it. I've closed the connection and the object is being retrieved properly. Check it out.
